import {
  Atom,
  BookOpen,
  Brain,
  Calculator,
  FlaskConical,
  Globe2,
  Landmark,
  Leaf,
  MessageSquareText,
  Triangle,
  Pi,
  Scale,
  Sigma,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

export type Course = {
  slug: string;
  name: string;
  description: string;
  teacher: string;
  level: "Básico" | "Intermedio" | "Avanzado";
  progress: number;
  lessons: number;
  completedLessons: number;
  hoursLeft: number;
  icon: LucideIcon;
  tone: "primary" | "success" | "warning" | "deep";
};

export const courses: Course[] = [
  {
    slug: "matematicas",
    name: "Matemáticas",
    description: "Álgebra, aritmética y geometría analítica",
    teacher: "Prof. Elena Quispe",
    level: "Avanzado",
    progress: 75,
    lessons: 48,
    completedLessons: 36,
    hoursLeft: 9,
    icon: Calculator,
    tone: "primary",
  },
  {
    slug: "razonamiento-matematico",
    name: "Razonamiento Matemático",
    description: "Sucesiones, planteo de ecuaciones y conteo",
    teacher: "Prof. Iván Rojas",
    level: "Intermedio",
    progress: 0,
    lessons: 70,
    completedLessons: 25,
    hoursLeft: 12,
    icon: Brain,
    tone: "deep",
  },
  {
    slug: "razonamiento-verbal",
    name: "Razonamiento Verbal",
    description: "Comprensión lectora, sinónimos y analogías",
    teacher: "Prof. Lucía Ayala",
    level: "Intermedio",
    progress: 70,
    lessons: 34,
    completedLessons: 24,
    hoursLeft: 7,
    icon: MessageSquareText,
    tone: "success",
  },
  {
    slug: "fisica",
    name: "Física",
    description: "Dinámica, movimiento y termodinámica",
    teacher: "Prof. Marco Vera",
    level: "Avanzado",
    progress: 60,
    lessons: 36,
    completedLessons: 22,
    hoursLeft: 11,
    icon: Atom,
    tone: "primary",
  },
  {
    slug: "quimica",
    name: "Química",
    description: "Enlaces químicos y química orgánica",
    teacher: "Prof. Ana Salas",
    level: "Intermedio",
    progress: 40,
    lessons: 30,
    completedLessons: 12,
    hoursLeft: 14,
    icon: FlaskConical,
    tone: "warning",
  },
  {
    slug: "biologia",
    name: "Biología",
    description: "Biología celular, genética y ecología",
    teacher: "Prof. Rosa Meza",
    level: "Básico",
    progress: 30,
    lessons: 28,
    completedLessons: 8,
    hoursLeft: 16,
    icon: Leaf,
    tone: "success",
  },
  {
    slug: "literatura",
    name: "Literatura",
    description: "Corrientes literarias y obras clave",
    teacher: "Prof. Diego Ponce",
    level: "Básico",
    progress: 45,
    lessons: 22,
    completedLessons: 10,
    hoursLeft: 6,
    icon: BookOpen,
    tone: "deep",
  },
  {
    slug: "historia",
    name: "Historia",
    description: "Historia del Perú y del mundo para exámenes de admisión",
    teacher: "Prof. Sofía Nieto",
    level: "Intermedio",
    progress: 0,
    lessons: 72,
    completedLessons: 0,
    hoursLeft: 72,
    icon: Landmark,
    tone: "warning",
  },
  {
    slug: "geografia",
    name: "Geografía",
    description: "Geografía del Perú y geografía general",
    teacher: "Prof. Hugo Lévano",
    level: "Básico",
    progress: 55,
    lessons: 20,
    completedLessons: 11,
    hoursLeft: 5,
    icon: Globe2,
    tone: "primary",
  },
  {
    slug: "cokito-rm",
    name: "Razonamiento Matemático - Cokito RM",
    description: "70 temas de razonamiento matemático para exámenes de admisión",
    teacher: "John Mamani M. (Academia GAUUS)",
    level: "Intermedio",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 45,
    icon: Brain,
    tone: "deep",
  },
  {
    slug: "geometria",
    name: "Geometría",
    description: "Geometría plana y del espacio para exámenes de admisión",
    teacher: "Didy Ricra Osorio (Ed. Cuzcano)",
    level: "Intermedio",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: Triangle,
    tone: "primary",
  },
  {
    slug: "aritmetica",
    name: "Aritmética",
    description: "Operaciones fundamentales, fracciones, porcentajes y problemas prácticos",
    teacher: "Prof. Elena Quispe",
    level: "Básico",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: Calculator,
    tone: "success",
  },
  {
    slug: "algebra",
    name: "Álgebra",
    description: "Ecuaciones, funciones, sistemas y álgebra abstracta",
    teacher: "Prof. Elena Quispe",
    level: "Intermedio",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: Sigma,
    tone: "primary",
  },
  {
    slug: "ciencia",
    name: "Ciencia",
    description: "Física, química, biología y ciencias aplicadas",
    teacher: "Prof. Ana Salas",
    level: "Intermedio",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: FlaskConical,
    tone: "warning",
  },
  {
    slug: "comprension-lectora",
    name: "Comprensión Lectora",
    description: "Lectura crítica, inferencia, análisis y comprensión de textos",
    teacher: "Prof. Laura Mendoza",
    level: "Básico",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: BookOpen,
    tone: "info",
  },
  {
    slug: "derecho-ciudadania",
    name: "Derecho y Ciudadanía",
    description: "Constitución, derechos humanos, poderes del Estado y participación ciudadana",
    teacher: "Prof. Carlos Ruiz",
    level: "Básico",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: Scale,
    tone: "primary",
  },
  {
    slug: "economia-basica",
    name: "Economía Básica",
    description: "Micro y macroeconomía, finanzas personales, impuestos y mercados",
    teacher: "Prof. María Torres",
    level: "Básico",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: TrendingUp,
    tone: "success",
  },
  {
    slug: "ingles",
    name: "Inglés",
    description: "Gramática, vocabulario, comprensión lectora y expresión oral",
    teacher: "Prof. James Wilson",
    level: "Básico",
    progress: 0,
    lessons: 70,
    completedLessons: 0,
    hoursLeft: 35,
    icon: Globe2,
    tone: "warning",
  },
];

export const lessons = [
  { title: "Introducción a las ecuaciones", state: "Completado" as const, minutes: 12 },
  { title: "Fórmula general", state: "En progreso" as const, minutes: 18 },
  { title: "Ejercicios prácticos", state: "Pendiente" as const, minutes: 25 },
  { title: "Aplicaciones en problemas", state: "Pendiente" as const, minutes: 22 },
  { title: "Repaso y autoevaluación", state: "Pendiente" as const, minutes: 30 },
];

export const courseLessons: Record<string, { title: string; state: "Completado" | "En progreso" | "Pendiente"; minutes: number }[]> = {
  "cokito-rm": [
    { title: "Relaciones de Parentesco", state: "Pendiente", minutes: 25 },
    { title: "Relaciones de Tiempo", state: "Pendiente", minutes: 20 },
    { title: "Verdades y Mentiras", state: "Pendiente", minutes: 22 },
    { title: "Orden de Información", state: "Pendiente", minutes: 18 },
    { title: "Razonamiento Inductivo", state: "Pendiente", minutes: 30 },
    { title: "Sistemas de Numeración", state: "Pendiente", minutes: 28 },
    { title: "Criptoaritmética", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones", state: "Pendiente", minutes: 22 },
    { title: "Analogías y Distribuciones", state: "Pendiente", minutes: 20 },
    { title: "Series", state: "Pendiente", minutes: 35 },
    { title: "Sumatorias", state: "Pendiente", minutes: 30 },
    { title: "Cuatro Operaciones", state: "Pendiente", minutes: 20 },
    { title: "Métodos Prácticos", state: "Pendiente", minutes: 25 },
    { title: "Planteo de Ecuaciones", state: "Pendiente", minutes: 28 },
    { title: "Edades", state: "Pendiente", minutes: 22 },
    { title: "Cronometría", state: "Pendiente", minutes: 18 },
    { title: "Promedios", state: "Pendiente", minutes: 20 },
    { title: "Operadores Matemáticos", state: "Pendiente", minutes: 25 },
    { title: "Operadores Binarios", state: "Pendiente", minutes: 22 },
    { title: "Conteo de Figuras", state: "Pendiente", minutes: 20 },
    { title: "Áreas Sombreadas y Perímetros", state: "Pendiente", minutes: 28 },
    { title: "Análisis Combinatorio", state: "Pendiente", minutes: 30 },
    { title: "Probabilidades", state: "Pendiente", minutes: 25 },
    { title: "Teoría de Conjuntos", state: "Pendiente", minutes: 25 },
    { title: "Diagramas de Venn", state: "Pendiente", minutes: 25 },
    { title: "Álgebra Booleana", state: "Pendiente", minutes: 25 },
    { title: "Tablas de Verdad", state: "Pendiente", minutes: 25 },
    { title: "Lógica Condicional", state: "Pendiente", minutes: 25 },
    { title: "Lógica Bicondicional", state: "Pendiente", minutes: 25 },
    { title: "Cuantificadores Lógicos", state: "Pendiente", minutes: 25 },
    { title: "Paradojas Lógicas", state: "Pendiente", minutes: 25 },
    { title: "Divisibilidad y Residuos", state: "Pendiente", minutes: 25 },
    { title: "MCM y MCD", state: "Pendiente", minutes: 25 },
    { title: "Congruencias Modulares", state: "Pendiente", minutes: 25 },
    { title: "Primalidad y Factorización", state: "Pendiente", minutes: 25 },
    { title: "Propiedades de Potencias", state: "Pendiente", minutes: 25 },
    { title: "Igualdades Notables", state: "Pendiente", minutes: 25 },
    { title: "Desigualdades Elementales", state: "Pendiente", minutes: 25 },
    { title: "Raíces y Racionales", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Mezclas", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Trabajo y Tiempo", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Velocidad", state: "Pendiente", minutes: 25 },
    { title: "Problemas Financieros", state: "Pendiente", minutes: 25 },
    { title: "Porcentajes y Tantos", state: "Pendiente", minutes: 25 },
    { title: "Proporcionalidad", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Densidad", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Edad Avanzados", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones Aritméticas", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones Geométricas", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones Recursivas", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones Recurrentes", state: "Pendiente", minutes: 25 },
    { title: "Patrones Numéricos", state: "Pendiente", minutes: 25 },
    { title: "Conjeturas e Inducción", state: "Pendiente", minutes: 25 },
    { title: "Secuencias de Dos Variables", state: "Pendiente", minutes: 25 },
    { title: "Progresiones Avanzadas", state: "Pendiente", minutes: 25 },
    { title: "Permutaciones Simples", state: "Pendiente", minutes: 25 },
    { title: "Combinaciones Simples", state: "Pendiente", minutes: 25 },
    { title: "Permutaciones con Repetición", state: "Pendiente", minutes: 25 },
    { title: "Combinaciones con Repetición", state: "Pendiente", minutes: 25 },
    { title: "Inclusión-Exclusión", state: "Pendiente", minutes: 25 },
    { title: "Principio de Casos", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Colocación", state: "Pendiente", minutes: 25 },
    { title: "Polinomios Generadores", state: "Pendiente", minutes: 25 },
    { title: "Media, Mediana y Moda", state: "Pendiente", minutes: 25 },
    { title: "Varianza y Desviación", state: "Pendiente", minutes: 25 },
    { title: "Percentiles y Cuartiles", state: "Pendiente", minutes: 25 },
    { title: "Razonamiento Verbal Avanzado", state: "Pendiente", minutes: 25 },
    { title: "Razonamiento Abstracto", state: "Pendiente", minutes: 25 },
    { title: "Razonamiento Espacial", state: "Pendiente", minutes: 25 },
    { title: "Problemas Compuestos RM", state: "Pendiente", minutes: 30 },
  ],
  "geometria": [
    { title: "Línea Recta y Ángulos", state: "Pendiente", minutes: 20 },
    { title: "Triángulos", state: "Pendiente", minutes: 25 },
    { title: "Polígonos", state: "Pendiente", minutes: 22 },
    { title: "Cuadriláteros", state: "Pendiente", minutes: 20 },
    { title: "Circunferencia", state: "Pendiente", minutes: 28 },
    { title: "Puntos Notables", state: "Pendiente", minutes: 25 },
    { title: "Proporcionalidad y Semejanza", state: "Pendiente", minutes: 30 },
    { title: "Relaciones Métricas", state: "Pendiente", minutes: 22 },
    { title: "Polígonos Regulares", state: "Pendiente", minutes: 20 },
    { title: "Áreas", state: "Pendiente", minutes: 25 },
    { title: "Rectas y Planos", state: "Pendiente", minutes: 28 },
    { title: "Prisma y Cilindro", state: "Pendiente", minutes: 22 },
    { title: "Pirámide y Cono", state: "Pendiente", minutes: 22 },
    { title: "Esfera", state: "Pendiente", minutes: 18 },
    { title: "La Recta", state: "Pendiente", minutes: 15 },
    { title: "Circunferencia y Parábola", state: "Pendiente", minutes: 25 },
    { title: "Elipse e Hipérbola", state: "Pendiente", minutes: 25 },
    { title: "Pitágoras y Aplicaciones", state: "Pendiente", minutes: 25 },
    { title: "Teorema de Tales", state: "Pendiente", minutes: 25 },
    { title: "Semejanza Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Criterios de Congruencia", state: "Pendiente", minutes: 25 },
    { title: "Área de Triángulos Avanzado", state: "Pendiente", minutes: 25 },
    { title: "Circunferencia Circunscrita e Inscrita", state: "Pendiente", minutes: 25 },
    { title: "Potencia de un Punto", state: "Pendiente", minutes: 25 },
    { title: "Ángulos Inscritos y Centrales", state: "Pendiente", minutes: 25 },
    { title: "Transformaciones Isométricas", state: "Pendiente", minutes: 25 },
    { title: "Simetría de Ejes y Puntos", state: "Pendiente", minutes: 25 },
    { title: "Homotecia", state: "Pendiente", minutes: 25 },
    { title: "Coordenadas Cartesianas", state: "Pendiente", minutes: 25 },
    { title: "Área en Coordenadas", state: "Pendiente", minutes: 25 },
    { title: "Recta en Coordenadas", state: "Pendiente", minutes: 25 },
    { title: "Circunferencia en Coordenadas", state: "Pendiente", minutes: 25 },
    { title: "Distancia Punto-Recta", state: "Pendiente", minutes: 25 },
    { title: "Razones Trigonométricas", state: "Pendiente", minutes: 25 },
    { title: "Identidades Trigonométricas", state: "Pendiente", minutes: 25 },
    { title: "Suma y Diferencia Trig", state: "Pendiente", minutes: 25 },
    { title: "Ley de Senos", state: "Pendiente", minutes: 25 },
    { title: "Ley de Cosenos", state: "Pendiente", minutes: 25 },
    { title: "Área con Trigonometría", state: "Pendiente", minutes: 25 },
    { title: "Ecuaciones Trigonométricas", state: "Pendiente", minutes: 25 },
    { title: "Aplicaciones Trigonométricas", state: "Pendiente", minutes: 25 },
    { title: "Vectores en el Plano", state: "Pendiente", minutes: 25 },
    { title: "Operaciones con Vectores", state: "Pendiente", minutes: 25 },
    { title: "Producto Escalar", state: "Pendiente", minutes: 25 },
    { title: "Rectas Vectorial", state: "Pendiente", minutes: 25 },
    { title: "Elipse Analítica", state: "Pendiente", minutes: 25 },
    { title: "Hipérbola Analítica", state: "Pendiente", minutes: 25 },
    { title: "Parábola Analítica", state: "Pendiente", minutes: 25 },
    { title: "Locus Geométrico", state: "Pendiente", minutes: 25 },
    { title: "Tangentes a Circunferencia", state: "Pendiente", minutes: 25 },
    { title: "Polígonos Inscritos y Circunscritos", state: "Pendiente", minutes: 25 },
    { title: "Sólidos Compuestos", state: "Pendiente", minutes: 25 },
    { title: "Secciones de Sólidos", state: "Pendiente", minutes: 25 },
    { title: "Áreas Superficiales Avanzado", state: "Pendiente", minutes: 25 },
    { title: "Volúmenes Avanzados", state: "Pendiente", minutes: 25 },
    { title: "Recta y Plano en el Espacio", state: "Pendiente", minutes: 25 },
    { title: "Ángulos en el Espacio", state: "Pendiente", minutes: 25 },
    { title: "Teorema de Ptolomeo", state: "Pendiente", minutes: 25 },
    { title: "Teorema de Stewart", state: "Pendiente", minutes: 25 },
    { title: "Circunferencia de los Nueve Puntos", state: "Pendiente", minutes: 25 },
    { title: "Triángulo de Euler", state: "Pendiente", minutes: 25 },
    { title: "Geometría Inversiva", state: "Pendiente", minutes: 25 },
    { title: "Números Complejos y Geometría", state: "Pendiente", minutes: 25 },
    { title: "Coordenadas Polares", state: "Pendiente", minutes: 25 },
    { title: "Curvas Notables", state: "Pendiente", minutes: 25 },
    { title: "Métodos de Resolución Geométrica", state: "Pendiente", minutes: 25 },
    { title: "Problemas Compuestos Geometría", state: "Pendiente", minutes: 25 },
    { title: "Optimización Geométrica", state: "Pendiente", minutes: 25 },
    { title: "Fractales: Introducción", state: "Pendiente", minutes: 25 },
    { title: "Estimación Geométrica", state: "Pendiente", minutes: 25 },
  ],
  "historia": [
    { title: "Civilizaciones Preincaicas", state: "Pendiente", minutes: 25 },
    { title: "Tahuantinsuyo", state: "Pendiente", minutes: 25 },
    { title: "Conquista Española", state: "Pendiente", minutes: 22 },
    { title: "Virreinato del Perú", state: "Pendiente", minutes: 25 },
    { title: "Independencia del Perú", state: "Pendiente", minutes: 28 },
    { title: "República Temprana", state: "Pendiente", minutes: 22 },
    { title: "Guano y Salitre", state: "Pendiente", minutes: 25 },
    { title: "Oncenio y Guerra", state: "Pendiente", minutes: 20 },
    { title: "Aprismo y Guerra", state: "Pendiente", minutes: 25 },
    { title: "Segundo Militarismo", state: "Pendiente", minutes: 22 },
    { title: "Primer Belaúnde", state: "Pendiente", minutes: 20 },
    { title: "Velasco y Reforma", state: "Pendiente", minutes: 28 },
    { title: "Terrorismo y Dictadura", state: "Pendiente", minutes: 30 },
    { title: "Transición Democrática", state: "Pendiente", minutes: 25 },
    { title: "Perú Contemporáneo", state: "Pendiente", minutes: 22 },
    { title: "Derechos Humanos", state: "Pendiente", minutes: 25 },
    { title: "Revolución Francesa", state: "Pendiente", minutes: 28 },
    { title: "Revoluciones Industriales", state: "Pendiente", minutes: 25 },
    { title: "Imperialismo y Colonialismo", state: "Pendiente", minutes: 22 },
    { title: "Primera Guerra Mundial", state: "Pendiente", minutes: 28 },
    { title: "Revolución Rusa", state: "Pendiente", minutes: 25 },
    { title: "Segunda Guerra Mundial", state: "Pendiente", minutes: 30 },
    { title: "Guerra Fría y Globalización", state: "Pendiente", minutes: 25 },
    { title: "Cultura Wari y Tiwanaku", state: "Pendiente", minutes: 25 },
    { title: "Señoríos Regionales", state: "Pendiente", minutes: 25 },
    { title: "Culturas Costeras Detalladas", state: "Pendiente", minutes: 25 },
    { title: "Agricultura Andina", state: "Pendiente", minutes: 25 },
    { title: "Qhapaq Ñan – Caminos", state: "Pendiente", minutes: 25 },
    { title: "Económica Incaica", state: "Pendiente", minutes: 25 },
    { title: "Guerra Civil – Atahualpa", state: "Pendiente", minutes: 25 },
    { title: "Resistencia – Manco Inca", state: "Pendiente", minutes: 25 },
    { title: "Batalla de Cajamarca", state: "Pendiente", minutes: 25 },
    { title: "Guerras Civiles Incas", state: "Pendiente", minutes: 25 },
    { title: "Virreinato Temprano", state: "Pendiente", minutes: 25 },
    { title: "Encomienda y Repartimiento", state: "Pendiente", minutes: 25 },
    { title: "Economía Colonial – Minería", state: "Pendiente", minutes: 25 },
    { title: "Sociedad Colonial – Castas", state: "Pendiente", minutes: 25 },
    { title: "Contrabando Colonial", state: "Pendiente", minutes: 25 },
    { title: "Reformas Borbónicas", state: "Pendiente", minutes: 25 },
    { title: "Rebelión de Túpac Amaru II", state: "Pendiente", minutes: 25 },
    { title: "Rebeliones Coloniales", state: "Pendiente", minutes: 25 },
    { title: "San Martín y Bolívar", state: "Pendiente", minutes: 25 },
    { title: "Batallas de la Independencia", state: "Pendiente", minutes: 25 },
    { title: "Constituciones Primitivas", state: "Pendiente", minutes: 25 },
    { title: "Consolidación Republicana", state: "Pendiente", minutes: 25 },
    { title: "Guerras Civiles XIX", state: "Pendiente", minutes: 25 },
    { title: "Economía Guanera", state: "Pendiente", minutes: 25 },
    { title: "Guerra del Pacífico", state: "Pendiente", minutes: 28 },
    { title: "Guerra del Pacífico – Consecuencias", state: "Pendiente", minutes: 25 },
    { title: "Generación 900", state: "Pendiente", minutes: 25 },
    { title: "Oligarquía Exportadora", state: "Pendiente", minutes: 25 },
    { title: "Crisis de 1929", state: "Pendiente", minutes: 25 },
    { title: "Segundo Gobierno de Ingenieros", state: "Pendiente", minutes: 25 },
    { title: "Gobierno del 45", state: "Pendiente", minutes: 25 },
    { title: "Dictadura de Odría", state: "Pendiente", minutes: 25 },
    { title: "Segundo Belaúnde", state: "Pendiente", minutes: 25 },
    { title: "Velasco – Reformismo Militar", state: "Pendiente", minutes: 28 },
    { title: "Velasco – Consecuencias", state: "Pendiente", minutes: 25 },
    { title: "Morales Bermúdez", state: "Pendiente", minutes: 25 },
    { title: "Sendero – Orígenes", state: "Pendiente", minutes: 30 },
    { title: "Sendero – Expansión", state: "Pendiente", minutes: 30 },
    { title: "Crisis de los 80", state: "Pendiente", minutes: 25 },
    { title: "Fujimori – Dictadura", state: "Pendiente", minutes: 28 },
    { title: "Corrupción Colonial", state: "Pendiente", minutes: 25 },
    { title: "Corrupción Republicana", state: "Pendiente", minutes: 25 },
    { title: "Historia Económica del Perú", state: "Pendiente", minutes: 25 },
    { title: "Historia de la Educación", state: "Pendiente", minutes: 25 },
    { title: "Historia de la Minería", state: "Pendiente", minutes: 25 },
    { title: "Movimientos Sociales", state: "Pendiente", minutes: 25 },
    { title: "Derechos Humanos – Historia", state: "Pendiente", minutes: 28 },
    { title: "Perú Contemporáneo – Problemas", state: "Pendiente", minutes: 25 },
    { title: "Bicentenario e Identidad", state: "Pendiente", minutes: 25 },
  ],
  "aritmetica": [
    { title: "Numeros Naturales", state: "Pendiente", minutes: 20 },
    { title: "Operaciones Basicas", state: "Pendiente", minutes: 20 },
    { title: "Fracciones y Decimales", state: "Pendiente", minutes: 22 },
    { title: "Porcentajes", state: "Pendiente", minutes: 22 },
    { title: "Proporcionalidad", state: "Pendiente", minutes: 25 },
    { title: "Regla de Tres", state: "Pendiente", minutes: 22 },
    { title: "Problemas de Mezcla", state: "Pendiente", minutes: 25 },
    { title: "MCM y MCD", state: "Pendiente", minutes: 22 },
    { title: "Divisibilidad", state: "Pendiente", minutes: 22 },
    { title: "Progresiones", state: "Pendiente", minutes: 25 },
    { title: "Probabilidad Basica", state: "Pendiente", minutes: 25 },
    { title: "Estadistica Descriptiva", state: "Pendiente", minutes: 25 },
    { title: "Productos Notables", state: "Pendiente", minutes: 22 },
    { title: "Factorizacion", state: "Pendiente", minutes: 22 },
    { title: "Combinatoria", state: "Pendiente", minutes: 25 },
    { title: "Logica y Conjuntos", state: "Pendiente", minutes: 25 },
    { title: "Numeros Primos", state: "Pendiente", minutes: 22 },
    { title: "Congruencia Modular", state: "Pendiente", minutes: 25 },
    { title: "Sumatorias", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones y Patrones", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Edad", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Dinero", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Velocidad", state: "Pendiente", minutes: 25 },
    { title: "Promedios y Medias", state: "Pendiente", minutes: 22 },
    { title: "Matematicas Sociales", state: "Pendiente", minutes: 25 },
    { title: "Valor Absoluto", state: "Pendiente", minutes: 20 },
    { title: "Raices y Radicales", state: "Pendiente", minutes: 22 },
    { title: "Potencias y Exponentes", state: "Pendiente", minutes: 22 },
    { title: "Notacion Cientifica", state: "Pendiente", minutes: 20 },
    { title: "Cifras Significativas", state: "Pendiente", minutes: 20 },
    { title: "Recta Numerica", state: "Pendiente", minutes: 20 },
    { title: "Comparar y Ordenar", state: "Pendiente", minutes: 20 },
    { title: "Densidad y Mediciones", state: "Pendiente", minutes: 22 },
    { title: "Ecuaciones Lineales", state: "Pendiente", minutes: 22 },
    { title: "Ecuaciones Cuadraticas", state: "Pendiente", minutes: 25 },
    { title: "Sistemas de Ecuaciones", state: "Pendiente", minutes: 25 },
    { title: "Inecuaciones", state: "Pendiente", minutes: 22 },
    { title: "Razonamiento Matematico", state: "Pendiente", minutes: 25 },
    { title: "Seriaciones", state: "Pendiente", minutes: 25 },
    { title: "Estimaciones y Redondeo", state: "Pendiente", minutes: 20 },
    { title: "Errores y Aproximaciones", state: "Pendiente", minutes: 22 },
    { title: "Numeros Enteros", state: "Pendiente", minutes: 20 },
    { title: "Pares e Impares", state: "Pendiente", minutes: 20 },
    { title: "Multiplos y Divisibles", state: "Pendiente", minutes: 22 },
    { title: "Suma de Digitos", state: "Pendiente", minutes: 20 },
    { title: "Division Larga", state: "Pendiente", minutes: 22 },
    { title: "Multiplicacion Avanzada", state: "Pendiente", minutes: 20 },
    { title: "Medidas y Unidades", state: "Pendiente", minutes: 20 },
    { title: "Conversion de Unidades", state: "Pendiente", minutes: 22 },
    { title: "Factorial", state: "Pendiente", minutes: 22 },
    { title: "Coeficiente Binomial", state: "Pendiente", minutes: 25 },
    { title: "Induccion Matematica", state: "Pendiente", minutes: 28 },
    { title: "Numeros Complejos", state: "Pendiente", minutes: 25 },
    { title: "Matrices Basicas", state: "Pendiente", minutes: 25 },
    { title: "Determinantes", state: "Pendiente", minutes: 25 },
    { title: "Conjuntos Aritmetica", state: "Pendiente", minutes: 25 },
    { title: "Logica Aritmetica", state: "Pendiente", minutes: 25 },
    { title: "Numeracion y Sistemas", state: "Pendiente", minutes: 22 },
    { title: "Productoria", state: "Pendiente", minutes: 22 },
    { title: "Fibonacci", state: "Pendiente", minutes: 22 },
    { title: "Problemas de Edad Avanzados", state: "Pendiente", minutes: 25 },
    { title: "Problemas de Tiempo", state: "Pendiente", minutes: 25 },
    { title: "Trabajo y Tiempo", state: "Pendiente", minutes: 25 },
    { title: "Proporciones en Examenes", state: "Pendiente", minutes: 25 },
    { title: "Promedio Ponderado", state: "Pendiente", minutes: 22 },
    { title: "Cronologia", state: "Pendiente", minutes: 22 },
    { title: "Peso y Volumen", state: "Pendiente", minutes: 22 },
    { title: "Comparar Numeros", state: "Pendiente", minutes: 20 },
    { title: "Resumen General Aritmetica", state: "Pendiente", minutes: 30 },
  ],
  "algebra": [
    { title: "Expresiones Algebraicas", state: "Pendiente", minutes: 22 },
    { title: "Ecuaciones Basicas", state: "Pendiente", minutes: 22 },
    { title: "Ecuaciones Lineales", state: "Pendiente", minutes: 22 },
    { title: "Desigualdades", state: "Pendiente", minutes: 22 },
    { title: "Propiedades Algebraicas", state: "Pendiente", minutes: 22 },
    { title: "Productos Notables", state: "Pendiente", minutes: 22 },
    { title: "Factorizacion", state: "Pendiente", minutes: 22 },
    { title: "Fracciones Algebraicas", state: "Pendiente", minutes: 25 },
    { title: "Raices y Radicales", state: "Pendiente", minutes: 22 },
    { title: "Leyes de los Exponentes", state: "Pendiente", minutes: 22 },
    { title: "Logaritmos", state: "Pendiente", minutes: 25 },
    { title: "Sistemas 2x2", state: "Pendiente", minutes: 25 },
    { title: "Sistemas 3x3", state: "Pendiente", minutes: 28 },
    { title: "Funciones Basicas", state: "Pendiente", minutes: 22 },
    { title: "Funciones Lineales", state: "Pendiente", minutes: 22 },
    { title: "Funciones Cuadraticas", state: "Pendiente", minutes: 25 },
    { title: "Polinomios", state: "Pendiente", minutes: 25 },
    { title: "Funciones Racionales", state: "Pendiente", minutes: 25 },
    { title: "Valores Absolutos", state: "Pendiente", minutes: 22 },
    { title: "Progresiones Avanzadas", state: "Pendiente", minutes: 25 },
    { title: "Sucesiones Algebraicas", state: "Pendiente", minutes: 25 },
    { title: "Numeros Complejos", state: "Pendiente", minutes: 28 },
    { title: "Matrices", state: "Pendiente", minutes: 25 },
    { title: "Determinantes", state: "Pendiente", minutes: 25 },
    { title: "Conjuntos", state: "Pendiente", minutes: 25 },
    { title: "Relaciones Algebraicas", state: "Pendiente", minutes: 25 },
    { title: "Logica Matematica", state: "Pendiente", minutes: 25 },
    { title: "Sistemas de Numeracion", state: "Pendiente", minutes: 22 },
    { title: "Operaciones Basicas", state: "Pendiente", minutes: 20 },
    { title: "Aproximaciones", state: "Pendiente", minutes: 22 },
    { title: "Ecuaciones Fraccionarias", state: "Pendiente", minutes: 25 },
    { title: "Ecuaciones Potencia", state: "Pendiente", minutes: 25 },
    { title: "Ecuaciones Logaritmicas", state: "Pendiente", minutes: 25 },
    { title: "Ecuaciones Exponenciales", state: "Pendiente", minutes: 25 },
    { title: "Valor Absoluto Avanzado", state: "Pendiente", minutes: 25 },
    { title: "Sistemas No Lineales", state: "Pendiente", minutes: 28 },
    { title: "Funciones Inversas", state: "Pendiente", minutes: 25 },
    { title: "Composicion de Funciones", state: "Pendiente", minutes: 25 },
    { title: "Funciones a Trozos", state: "Pendiente", minutes: 25 },
    { title: "Division de Polinomios", state: "Pendiente", minutes: 25 },
    { title: "Razones y Proporciones", state: "Pendiente", minutes: 22 },
    { title: "Potenciacion Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Congruencia Modular", state: "Pendiente", minutes: 25 },
    { title: "Arreglos y Matrices", state: "Pendiente", minutes: 25 },
    { title: "Sumatoria", state: "Pendiente", minutes: 25 },
    { title: "Induccion Matematica", state: "Pendiente", minutes: 28 },
    { title: "Numeros Especiales", state: "Pendiente", minutes: 25 },
    { title: "Combinatoria Algebraica", state: "Pendiente", minutes: 25 },
    { title: "Funciones Trigonometricas", state: "Pendiente", minutes: 25 },
    { title: "Expresiones Log-Exp", state: "Pendiente", minutes: 25 },
    { title: "Funciones Especiales", state: "Pendiente", minutes: 25 },
    { title: "Topicos Avanzados", state: "Pendiente", minutes: 28 },
    { title: "Ecuaciones Recurrentes", state: "Pendiente", minutes: 25 },
    { title: "Identidades Algebraicas", state: "Pendiente", minutes: 25 },
    { title: "Optimizacion", state: "Pendiente", minutes: 28 },
    { title: "Aproximaciones Avanzadas", state: "Pendiente", minutes: 25 },
    { title: "Modelos Algebraicos", state: "Pendiente", minutes: 25 },
    { title: "Logica Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Conjuntos Avanzados", state: "Pendiente", minutes: 25 },
    { title: "Secuencias y Patrones", state: "Pendiente", minutes: 25 },
    { title: "Geometria Analitica", state: "Pendiente", minutes: 25 },
    { title: "Trigonometria Completa", state: "Pendiente", minutes: 25 },
    { title: "Vectores", state: "Pendiente", minutes: 25 },
    { title: "Examenes de Admision", state: "Pendiente", minutes: 30 },
    { title: "Inecuaciones Avanzadas", state: "Pendiente", minutes: 25 },
    { title: "Estadistica para Examenes", state: "Pendiente", minutes: 25 },
    { title: "Division Sintetica", state: "Pendiente", minutes: 22 },
    { title: "Resumen Algebra Final", state: "Pendiente", minutes: 30 },
  ],
  "ciencia": [
    { title: "El Universo", state: "Pendiente", minutes: 25 },
    { title: "Estructura Atomica", state: "Pendiente", minutes: 22 },
    { title: "Tabla Periodica", state: "Pendiente", minutes: 22 },
    { title: "Enlaces Quimicos", state: "Pendiente", minutes: 25 },
    { title: "Reacciones Quimicas", state: "Pendiente", minutes: 25 },
    { title: "Estoicometria", state: "Pendiente", minutes: 25 },
    { title: "Acidos y Bases", state: "Pendiente", minutes: 25 },
    { title: "Soluciones", state: "Pendiente", minutes: 25 },
    { title: "Termoquimica", state: "Pendiente", minutes: 25 },
    { title: "Oxidacion y Reduccion", state: "Pendiente", minutes: 25 },
    { title: "Quimica Organica", state: "Pendiente", minutes: 25 },
    { title: "Nomenclatura Quimica", state: "Pendiente", minutes: 22 },
    { title: "Leyes de los Gases", state: "Pendiente", minutes: 25 },
    { title: "Quimica para Examenes", state: "Pendiente", minutes: 30 },
    { title: "La Celula", state: "Pendiente", minutes: 22 },
    { title: "Genetica", state: "Pendiente", minutes: 25 },
    { title: "Evolucion", state: "Pendiente", minutes: 25 },
    { title: "Ecologia", state: "Pendiente", minutes: 25 },
    { title: "Biotecnologia", state: "Pendiente", minutes: 25 },
    { title: "Sistema Solar", state: "Pendiente", minutes: 22 },
    { title: "Tectonica de Placas", state: "Pendiente", minutes: 25 },
    { title: "Clima y Tiempo", state: "Pendiente", minutes: 25 },
    { title: "Recursos Naturales", state: "Pendiente", minutes: 25 },
    { title: "Ciencia para Examenes", state: "Pendiente", minutes: 30 },
    { title: "Mecanica Basica", state: "Pendiente", minutes: 25 },
    { title: "Leyes de Conservacion", state: "Pendiente", minutes: 25 },
    { title: "Fluidos", state: "Pendiente", minutes: 25 },
    { title: "Calor y Termodinamica", state: "Pendiente", minutes: 25 },
    { title: "Electricidad Basica", state: "Pendiente", minutes: 25 },
    { title: "Ondas y Sonido", state: "Pendiente", minutes: 25 },
    { title: "Optica", state: "Pendiente", minutes: 25 },
    { title: "Magnetismo", state: "Pendiente", minutes: 25 },
    { title: "Fisica Moderna", state: "Pendiente", minutes: 28 },
    { title: "Quimica Avanzada Examenes", state: "Pendiente", minutes: 30 },
    { title: "Biologia Celular Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Biologia Molecular", state: "Pendiente", minutes: 25 },
    { title: "Sistemas Biologicos", state: "Pendiente", minutes: 25 },
    { title: "Reproduccion y Desarrollo", state: "Pendiente", minutes: 25 },
    { title: "Ecologia Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Ciencia Ambiental", state: "Pendiente", minutes: 25 },
    { title: "Geologia General", state: "Pendiente", minutes: 25 },
    { title: "Astronomia General", state: "Pendiente", minutes: 25 },
    { title: "Meteorologia", state: "Pendiente", minutes: 25 },
    { title: "Oceanografia", state: "Pendiente", minutes: 25 },
    { title: "Biologia Marina", state: "Pendiente", minutes: 25 },
    { title: "Nutricion", state: "Pendiente", minutes: 25 },
    { title: "Farmacologia Basica", state: "Pendiente", minutes: 25 },
    { title: "Ecologia Humana", state: "Pendiente", minutes: 25 },
    { title: "Biologia Evolutiva", state: "Pendiente", minutes: 25 },
    { title: "Quimica Basica Examenes", state: "Pendiente", minutes: 30 },
    { title: "Genetica Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Microbiologia", state: "Pendiente", minutes: 25 },
    { title: "Patologia General", state: "Pendiente", minutes: 25 },
    { title: "Ciencia Av Examenes", state: "Pendiente", minutes: 30 },
    { title: "Robotica y Tecnologia", state: "Pendiente", minutes: 25 },
    { title: "Energias Renovables", state: "Pendiente", minutes: 25 },
    { title: "Biotecnologia Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Neurociencia", state: "Pendiente", minutes: 25 },
    { title: "Ciencia de Datos", state: "Pendiente", minutes: 25 },
    { title: "Terminologia Cientifica", state: "Pendiente", minutes: 22 },
    { title: "Metodo Cientifico", state: "Pendiente", minutes: 22 },
    { title: "Ecosistemas del Peru", state: "Pendiente", minutes: 25 },
    { title: "Biologia Vegetal", state: "Pendiente", minutes: 25 },
    { title: "Zoologia Basica", state: "Pendiente", minutes: 25 },
    { title: "Historia de la Ciencia", state: "Pendiente", minutes: 25 },
    { title: "Resumen Ciencia Final", state: "Pendiente", minutes: 30 },
  ],
  "comprension-lectora": [
    { title: "Idea Principal", state: "Pendiente", minutes: 20 },
    { title: "Ideas Secundarias", state: "Pendiente", minutes: 20 },
    { title: "Inferencia", state: "Pendiente", minutes: 22 },
    { title: "Vocabulario en Contexto", state: "Pendiente", minutes: 22 },
    { title: "Proposito del Autor", state: "Pendiente", minutes: 25 },
    { title: "Estructura del Texto", state: "Pendiente", minutes: 25 },
    { title: "Conectores y Marcadores", state: "Pendiente", minutes: 22 },
    { title: "Tono y Actitud", state: "Pendiente", minutes: 22 },
    { title: "Argumentacion", state: "Pendiente", minutes: 25 },
    { title: "Resumen y Sintesis", state: "Pendiente", minutes: 25 },
    { title: "Textos Comparativos", state: "Pendiente", minutes: 25 },
    { title: "Relacion Causa-Efecto", state: "Pendiente", minutes: 25 },
    { title: "Ordenamiento Temporal", state: "Pendiente", minutes: 25 },
    { title: "Clasificacion", state: "Pendiente", minutes: 25 },
    { title: "Problema y Solucion", state: "Pendiente", minutes: 25 },
    { title: "Textos Descriptivos", state: "Pendiente", minutes: 25 },
    { title: "Textos Narrativos", state: "Pendiente", minutes: 25 },
    { title: "Textos Persuasivos", state: "Pendiente", minutes: 25 },
    { title: "Ironia y Sentido Oculto", state: "Pendiente", minutes: 25 },
    { title: "Textos Academicos", state: "Pendiente", minutes: 25 },
    { title: "Inferencia Avanzada", state: "Pendiente", minutes: 28 },
    { title: "Evaluacion Critica", state: "Pendiente", minutes: 25 },
    { title: "Ortografia y Gramatica", state: "Pendiente", minutes: 22 },
    { title: "Precision Lectora", state: "Pendiente", minutes: 22 },
    { title: "Lectura Veloz", state: "Pendiente", minutes: 20 },
    { title: "Ambiguedad y Precision", state: "Pendiente", minutes: 22 },
    { title: "Inferencia en Literatura", state: "Pendiente", minutes: 25 },
    { title: "Tecnicas de Lectura", state: "Pendiente", minutes: 25 },
    { title: "Tema Central del Texto", state: "Pendiente", minutes: 22 },
    { title: "Conclusiones del Autor", state: "Pendiente", minutes: 22 },
    { title: "Narrativa Completa", state: "Pendiente", minutes: 25 },
    { title: "Texto Argumentativo", state: "Pendiente", minutes: 25 },
    { title: "Texto Expositivo", state: "Pendiente", minutes: 25 },
    { title: "Resumen Avanzado", state: "Pendiente", minutes: 25 },
    { title: "Parafrasis", state: "Pendiente", minutes: 22 },
    { title: "Analogias y Comparaciones", state: "Pendiente", minutes: 25 },
    { title: "Generalizaciones", state: "Pendiente", minutes: 22 },
    { title: "Textos de Contraste", state: "Pendiente", minutes: 25 },
    { title: "Secuenciacion", state: "Pendiente", minutes: 22 },
    { title: "Causalidad Compleja", state: "Pendiente", minutes: 25 },
    { title: "Tipos de Texto", state: "Pendiente", minutes: 22 },
    { title: "Tiempo Verbal", state: "Pendiente", minutes: 22 },
    { title: "Sujeto y Predicado", state: "Pendiente", minutes: 20 },
    { title: "Tipos de Oracion", state: "Pendiente", minutes: 22 },
    { title: "Cohesion Textual", state: "Pendiente", minutes: 22 },
    { title: "Textos Explicativos", state: "Pendiente", minutes: 22 },
    { title: "Ejemplificacion", state: "Pendiente", minutes: 22 },
    { title: "Interpretacion de Textos", state: "Pendiente", minutes: 25 },
    { title: "Resolucion de Examenes", state: "Pendiente", minutes: 25 },
    { title: "Comprension Global", state: "Pendiente", minutes: 25 },
    { title: "Lectura con Tiempo Limitado", state: "Pendiente", minutes: 20 },
    { title: "Multiples Fuentes", state: "Pendiente", minutes: 25 },
    { title: "Respuesta Exacta", state: "Pendiente", minutes: 22 },
    { title: "Repaso Comprension Lectora", state: "Pendiente", minutes: 30 },
    { title: "Contexto Historico", state: "Pendiente", minutes: 25 },
    { title: "Literatura Clasica", state: "Pendiente", minutes: 25 },
    { title: "Texto Cientifico", state: "Pendiente", minutes: 25 },
    { title: "Editorial", state: "Pendiente", minutes: 25 },
    { title: "Texto Informativo", state: "Pendiente", minutes: 25 },
    { title: "Analisis de Discurso", state: "Pendiente", minutes: 28 },
    { title: "Precision Avanzada", state: "Pendiente", minutes: 22 },
    { title: "Texto Persuasivo", state: "Pendiente", minutes: 25 },
    { title: "Vocabulario Avanzado", state: "Pendiente", minutes: 22 },
    { title: "Lo Implicito", state: "Pendiente", minutes: 25 },
    { title: "Ordenar Textos", state: "Pendiente", minutes: 22 },
    { title: "Evaluar Fuentes", state: "Pendiente", minutes: 25 },
    { title: "Resumen Mixto", state: "Pendiente", minutes: 25 },
    { title: "Narrativa Literaria", state: "Pendiente", minutes: 25 },
    { title: "Uso del Diccionario", state: "Pendiente", minutes: 20 },
    { title: "Contexto Cultural", state: "Pendiente", minutes: 25 },
    { title: "Evaluacion Final CL", state: "Pendiente", minutes: 30 },
  ],
  "derecho-ciudadania": [
    { title: "La Constitucion", state: "Pendiente", minutes: 25 },
    { title: "Derechos Humanos", state: "Pendiente", minutes: 25 },
    { title: "Derechos Sociales", state: "Pendiente", minutes: 25 },
    { title: "Obligaciones del Ciudadano", state: "Pendiente", minutes: 22 },
    { title: "Poderes del Estado", state: "Pendiente", minutes: 25 },
    { title: "El Congreso", state: "Pendiente", minutes: 25 },
    { title: "El Gobierno", state: "Pendiente", minutes: 25 },
    { title: "Poder Judicial", state: "Pendiente", minutes: 25 },
    { title: "Proceso Legislativo", state: "Pendiente", minutes: 25 },
    { title: "Tipos de Leyes", state: "Pendiente", minutes: 22 },
    { title: "Gobiernos Regionales", state: "Pendiente", minutes: 25 },
    { title: "Gobiernos Locales", state: "Pendiente", minutes: 25 },
    { title: "Participacion Ciudadana", state: "Pendiente", minutes: 22 },
    { title: "Control del Estado", state: "Pendiente", minutes: 25 },
    { title: "Tutela de Derechos", state: "Pendiente", minutes: 25 },
    { title: "Organos de Control", state: "Pendiente", minutes: 25 },
    { title: "Justicia Constitucional", state: "Pendiente", minutes: 25 },
    { title: "Derecho Penal", state: "Pendiente", minutes: 25 },
    { title: "Derecho Civil", state: "Pendiente", minutes: 25 },
    { title: "Derecho Laboral", state: "Pendiente", minutes: 25 },
    { title: "Derecho de Familia", state: "Pendiente", minutes: 25 },
    { title: "Personeria Juridica", state: "Pendiente", minutes: 22 },
    { title: "Organismos Autonomos", state: "Pendiente", minutes: 25 },
    { title: "Fiscalizacion del Estado", state: "Pendiente", minutes: 25 },
    { title: "Contrataciones Publicas", state: "Pendiente", minutes: 22 },
    { title: "Transparencia", state: "Pendiente", minutes: 22 },
    { title: "Buen Gobierno", state: "Pendiente", minutes: 22 },
    { title: "Mala Praxis Publica", state: "Pendiente", minutes: 25 },
    { title: "Justicia Gratuita", state: "Pendiente", minutes: 22 },
    { title: "Conflictos Territoriales", state: "Pendiente", minutes: 25 },
    { title: "Sistema Electoral", state: "Pendiente", minutes: 25 },
    { title: "Organos Electorales", state: "Pendiente", minutes: 22 },
    { title: "El Voto", state: "Pendiente", minutes: 22 },
    { title: "Partidos Politicos", state: "Pendiente", minutes: 25 },
    { title: "Ciudadania", state: "Pendiente", minutes: 22 },
    { title: "Democracia", state: "Pendiente", minutes: 25 },
    { title: "Estado Constitucional", state: "Pendiente", minutes: 25 },
    { title: "Tutela de Derechos Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Jurisdicciones Especiales", state: "Pendiente", minutes: 25 },
    { title: "Proceso Penal", state: "Pendiente", minutes: 25 },
    { title: "Sentencia Judicial", state: "Pendiente", minutes: 22 },
    { title: "Jurisprudencia", state: "Pendiente", minutes: 25 },
    { title: "Derechos Fundamentales", state: "Pendiente", minutes: 25 },
    { title: "Dignidad Humana", state: "Pendiente", minutes: 22 },
    { title: "Limites al Poder", state: "Pendiente", minutes: 25 },
    { title: "Justicia Social", state: "Pendiente", minutes: 25 },
    { title: "Bien Comun", state: "Pendiente", minutes: 22 },
    { title: "Vigilancia Ciudadana", state: "Pendiente", minutes: 22 },
    { title: "Historia Constitucional", state: "Pendiente", minutes: 25 },
    { title: "Conceptos Clave", state: "Pendiente", minutes: 22 },
    { title: "Preparacion para Examenes", state: "Pendiente", minutes: 30 },
    { title: "Resumen Derecho y Ciudadania", state: "Pendiente", minutes: 30 },
    { title: "Autonomia Regional", state: "Pendiente", minutes: 25 },
    { title: "Participacion y Voto", state: "Pendiente", minutes: 22 },
    { title: "Separacion de Poderes", state: "Pendiente", minutes: 25 },
    { title: "Derecho Ambiental", state: "Pendiente", minutes: 25 },
    { title: "Derecho Digital", state: "Pendiente", minutes: 25 },
    { title: "Justicia Transicional", state: "Pendiente", minutes: 28 },
    { title: "Propiedad Intelectual", state: "Pendiente", minutes: 25 },
    { title: "Responsabilidad Social", state: "Pendiente", minutes: 22 },
    { title: "Educacion Civica", state: "Pendiente", minutes: 22 },
    { title: "Habeas Corpus", state: "Pendiente", minutes: 22 },
    { title: "Amparo", state: "Pendiente", minutes: 22 },
    { title: "Habeas Data", state: "Pendiente", minutes: 22 },
    { title: "Evaluacion Final DC", state: "Pendiente", minutes: 30 },
    { title: "Actualidad Juridica", state: "Pendiente", minutes: 25 },
    { title: "Derechos Colectivos", state: "Pendiente", minutes: 25 },
    { title: "Gobierno Central", state: "Pendiente", minutes: 25 },
    { title: "Legislacion Especial", state: "Pendiente", minutes: 25 },
  ],
  "economia-basica": [
    { title: "Oferta y Demanda", state: "Pendiente", minutes: 22 },
    { title: "Formacion del Precio", state: "Pendiente", minutes: 22 },
    { title: "Tipos de Mercado", state: "Pendiente", minutes: 25 },
    { title: "Microeconomia", state: "Pendiente", minutes: 25 },
    { title: "Macroeconomia", state: "Pendiente", minutes: 25 },
    { title: "Producto Interno Bruto", state: "Pendiente", minutes: 25 },
    { title: "Inflacion", state: "Pendiente", minutes: 25 },
    { title: "Deflacion", state: "Pendiente", minutes: 22 },
    { title: "Desempleo", state: "Pendiente", minutes: 25 },
    { title: "Politica Monetaria", state: "Pendiente", minutes: 25 },
    { title: "Politica Fiscal", state: "Pendiente", minutes: 25 },
    { title: "Tipos de Impuestos", state: "Pendiente", minutes: 22 },
    { title: "El IGV", state: "Pendiente", minutes: 22 },
    { title: "Impuesto a la Renta", state: "Pendiente", minutes: 25 },
    { title: "Comercio Exterior", state: "Pendiente", minutes: 25 },
    { title: "Tipo de Cambio", state: "Pendiente", minutes: 22 },
    { title: "Sistema Financiero", state: "Pendiente", minutes: 25 },
    { title: "El Sistema Bancario", state: "Pendiente", minutes: 22 },
    { title: "Tasas de Interes", state: "Pendiente", minutes: 22 },
    { title: "Credito y Deuda", state: "Pendiente", minutes: 22 },
    { title: "Inversion", state: "Pendiente", minutes: 25 },
    { title: "Ahorro", state: "Pendiente", minutes: 20 },
    { title: "Finanzas Personales", state: "Pendiente", minutes: 25 },
    { title: "Presupuesto Personal", state: "Pendiente", minutes: 22 },
    { title: "Fuentes de Ingreso", state: "Pendiente", minutes: 20 },
    { title: "Tipos de Gasto", state: "Pendiente", minutes: 22 },
    { title: "Deuda Publica", state: "Pendiente", minutes: 25 },
    { title: "Riesgo Economico", state: "Pendiente", minutes: 25 },
    { title: "Competencia en el Mercado", state: "Pendiente", minutes: 25 },
    { title: "Bienes y Servicios", state: "Pendiente", minutes: 20 },
    { title: "Escasez y Eleccion", state: "Pendiente", minutes: 22 },
    { title: "Costo de Oportunidad", state: "Pendiente", minutes: 22 },
    { title: "Externalidades", state: "Pendiente", minutes: 25 },
    { title: "Subsidios y Contribuciones", state: "Pendiente", minutes: 22 },
    { title: "Globalizacion", state: "Pendiente", minutes: 25 },
    { title: "Monedas y Cambio", state: "Pendiente", minutes: 22 },
    { title: "Indicadores Economicos", state: "Pendiente", minutes: 25 },
    { title: "Desarrollo Economico", state: "Pendiente", minutes: 25 },
    { title: "Pobreza y Desigualdad", state: "Pendiente", minutes: 25 },
    { title: "Tipos de Empresa", state: "Pendiente", minutes: 22 },
    { title: "Empresa vs Persona Natural", state: "Pendiente", minutes: 22 },
    { title: "Cuenta Corriente", state: "Pendiente", minutes: 20 },
    { title: "Interes Simple", state: "Pendiente", minutes: 22 },
    { title: "Interes Compuesto", state: "Pendiente", minutes: 22 },
    { title: "Tipos de Inflacion", state: "Pendiente", minutes: 25 },
    { title: "Productividad", state: "Pendiente", minutes: 22 },
    { title: "Competitividad", state: "Pendiente", minutes: 22 },
    { title: "Tecnologia e Innovacion", state: "Pendiente", minutes: 25 },
    { title: "Economia Verde", state: "Pendiente", minutes: 25 },
    { title: "Finanzas Publicas", state: "Pendiente", minutes: 25 },
    { title: "Gasto Publico", state: "Pendiente", minutes: 22 },
    { title: "Recursos Naturales", state: "Pendiente", minutes: 25 },
    { title: "Economia de la Energia", state: "Pendiente", minutes: 25 },
    { title: "Transporte y Logistica", state: "Pendiente", minutes: 22 },
    { title: "Empleo Formal e Informal", state: "Pendiente", minutes: 22 },
    { title: "Preparacion Examenes", state: "Pendiente", minutes: 30 },
    { title: "Resumen Economia Basica", state: "Pendiente", minutes: 30 },
    { title: "Ingreso Nacional", state: "Pendiente", minutes: 25 },
    { title: "Curso de Vida Economico", state: "Pendiente", minutes: 25 },
    { title: "Clasificacion de Impuestos", state: "Pendiente", minutes: 22 },
    { title: "Mercado de Trabajo", state: "Pendiente", minutes: 25 },
    { title: "Patrimonio y Riqueza", state: "Pendiente", minutes: 25 },
    { title: "Tasa de Cambio", state: "Pendiente", minutes: 22 },
    { title: "Deuda Soberana", state: "Pendiente", minutes: 25 },
    { title: "Politica Comercial", state: "Pendiente", minutes: 25 },
    { title: "Indicadores Avanzados", state: "Pendiente", minutes: 25 },
    { title: "Economia Informal", state: "Pendiente", minutes: 25 },
    { title: "Crecimiento Economico", state: "Pendiente", minutes: 25 },
    { title: "Estabilidad Economica", state: "Pendiente", minutes: 25 },
  ],
  "ingles": [
    { title: "Vocabulario Basico", state: "Pendiente", minutes: 20 },
    { title: "Gramatica Basica", state: "Pendiente", minutes: 22 },
    { title: "Verbos Regulares", state: "Pendiente", minutes: 22 },
    { title: "Verbos Irregulares", state: "Pendiente", minutes: 25 },
    { title: "Presente Simple", state: "Pendiente", minutes: 22 },
    { title: "Pasado Simple", state: "Pendiente", minutes: 22 },
    { title: "Futuro con Will", state: "Pendiente", minutes: 22 },
    { title: "Presente Continuo", state: "Pendiente", minutes: 22 },
    { title: "Present Perfect", state: "Pendiente", minutes: 25 },
    { title: "Pasado Continuo", state: "Pendiente", minutes: 25 },
    { title: "Condicional", state: "Pendiente", minutes: 22 },
    { title: "Modales", state: "Pendiente", minutes: 22 },
    { title: "Articulos", state: "Pendiente", minutes: 20 },
    { title: "Preposiciones", state: "Pendiente", minutes: 20 },
    { title: "Pronombres", state: "Pendiente", minutes: 20 },
    { title: "Adjetivos", state: "Pendiente", minutes: 20 },
    { title: "Adverbios", state: "Pendiente", minutes: 20 },
    { title: "Formar Preguntas", state: "Pendiente", minutes: 22 },
    { title: "Formar Negacion", state: "Pendiente", minutes: 22 },
    { title: "Comprension de Textos", state: "Pendiente", minutes: 25 },
    { title: "Escritura Basica", state: "Pendiente", minutes: 25 },
    { title: "Comprension Auditiva", state: "Pendiente", minutes: 25 },
    { title: "Expresion Oral", state: "Pendiente", minutes: 25 },
    { title: "Phrasal Verbs", state: "Pendiente", minutes: 22 },
    { title: "Expresiones Idiomaticas", state: "Pendiente", minutes: 22 },
    { title: "Dialogos", state: "Pendiente", minutes: 22 },
    { title: "Vocabulario de Viaje", state: "Pendiente", minutes: 22 },
    { title: "Vocabulario de Trabajo", state: "Pendiente", minutes: 22 },
    { title: "Salud y Cuerpo", state: "Pendiente", minutes: 22 },
    { title: "Comida y Bebida", state: "Pendiente", minutes: 20 },
    { title: "La Familia", state: "Pendiente", minutes: 20 },
    { title: "La Escuela", state: "Pendiente", minutes: 20 },
    { title: "El Clima", state: "Pendiente", minutes: 20 },
    { title: "El Tiempo", state: "Pendiente", minutes: 20 },
    { title: "Numeros y Matematicas", state: "Pendiente", minutes: 20 },
    { title: "Direcciones", state: "Pendiente", minutes: 22 },
    { title: "Tecnologia", state: "Pendiente", minutes: 22 },
    { title: "Medio Ambiente", state: "Pendiente", minutes: 25 },
    { title: "Oraciones Relativas", state: "Pendiente", minutes: 25 },
    { title: "Voz Pasiva", state: "Pendiente", minutes: 25 },
    { title: "Reported Speech", state: "Pendiente", minutes: 25 },
    { title: "Tres Condicionales", state: "Pendiente", minutes: 25 },
    { title: "Gerundios", state: "Pendiente", minutes: 22 },
    { title: "Infinitivos", state: "Pendiente", minutes: 22 },
    { title: "Participios", state: "Pendiente", minutes: 22 },
    { title: "Conjunciones", state: "Pendiente", minutes: 22 },
    { title: "Determinantes", state: "Pendiente", minutes: 22 },
    { title: "Cuantificadores", state: "Pendiente", minutes: 22 },
    { title: "Conversaciones Complejas", state: "Pendiente", minutes: 28 },
    { title: "Escritura de Ensays", state: "Pendiente", minutes: 28 },
    { title: "Ingles Academico", state: "Pendiente", minutes: 25 },
    { title: "Preparacion Examenes", state: "Pendiente", minutes: 30 },
    { title: "Resumen Ingles", state: "Pendiente", minutes: 30 },
    { title: "Lenguaje Figurado", state: "Pendiente", minutes: 25 },
    { title: "Gramatica Avanzada", state: "Pendiente", minutes: 28 },
    { title: "Estructura de Ensayo", state: "Pendiente", minutes: 25 },
    { title: "Vocabulario de Investigacion", state: "Pendiente", minutes: 22 },
    { title: "Presentaciones", state: "Pendiente", minutes: 25 },
    { title: "Ingles de Negocios", state: "Pendiente", minutes: 25 },
    { title: "Medios de Comunicacion", state: "Pendiente", minutes: 25 },
    { title: "Ciencia en Ingles", state: "Pendiente", minutes: 25 },
    { title: "Temas Sociales", state: "Pendiente", minutes: 25 },
    { title: "Cultura y Sociedad", state: "Pendiente", minutes: 25 },
    { title: "Escritura Avanzada", state: "Pendiente", minutes: 28 },
    { title: "Correccion de Errores", state: "Pendiente", minutes: 22 },
    { title: "Velocidad de Lectura", state: "Pendiente", minutes: 20 },
    { title: "Vocabulario Universitario", state: "Pendiente", minutes: 22 },
    { title: "Conversacion Avanzada", state: "Pendiente", minutes: 25 },
    { title: "Prueba de Practica", state: "Pendiente", minutes: 30 },
  ],
};

export const upcoming = [
  {
    title: "Simulacro UNI",
    detail: "180 min · 100 preguntas",
    when: "Hoy, 16:00",
    tone: "warning" as const,
  },
  {
    title: "Entrega de tarea",
    detail: "Historia: La República Aristocrática",
    when: "Mañana, 10:00",
    tone: "primary" as const,
  },
  {
    title: "Clase en vivo: Física",
    detail: "Dinámica y movimiento",
    when: "25 Ago, 14:00",
    tone: "success" as const,
  },
];

export const mocks = [
  { name: "Simulacro UNI", questions: 100, minutes: 180, level: "Difícil", score: 86 },
  { name: "Simulacro San Marcos", questions: 100, minutes: 180, level: "Difícil", score: 78 },
  { name: "Simulacro Católica", questions: 80, minutes: 150, level: "Medio", score: 81 },
  { name: "Simulacro Ordinario", questions: 60, minutes: 120, level: "Fácil", score: 90 },
];

export const universities = [
  {
    name: "UNI",
    full: "Universidad Nacional de Ingeniería",
    score: 13.5,
    vacancies: 1200,
    date: "24 Sep",
    cost: "S/ 550",
  },
  {
    name: "UNMSM",
    full: "Universidad Nacional Mayor de San Marcos",
    score: 12.8,
    vacancies: 1450,
    date: "18 Sep",
    cost: "S/ 480",
  },
  {
    name: "PUCP",
    full: "Pontificia Universidad Católica del Perú",
    score: 14.2,
    vacancies: 900,
    date: "02 Oct",
    cost: "S/ 620",
  },
  {
    name: "UNSA",
    full: "Universidad Nacional de San Agustín",
    score: 12.1,
    vacancies: 1100,
    date: "11 Oct",
    cost: "S/ 400",
  },
];

export const strategies = [
  { title: "Pomodoro", detail: "Bloques de 25 min con descansos guiados", tag: "Enfoque" },
  { title: "Técnica Feynman", detail: "Explica el tema como si enseñaras", tag: "Memoria" },
  { title: "Hábitos", detail: "Construye tu rutina diaria de estudio", tag: "Constancia" },
  { title: "Planificador semanal", detail: "Organiza tus materias por bloques", tag: "Orden" },
  { title: "Control de ansiedad", detail: "Respiración y manejo de presión", tag: "Bienestar" },
  { title: "Gestión del tiempo", detail: "Prioriza con la matriz de Eisenhower", tag: "Orden" },
  { title: "Distracciones", detail: "Diseña un entorno libre de ruido", tag: "Enfoque" },
  { title: "Horarios", detail: "Encuentra tus horas de mayor rendimiento", tag: "Rutina" },
];

export const communityPosts = [
  {
    author: "Juan Pablo",
    ago: "hace 2 horas",
    text: "¿Alguien me explica el problema 18 del simulacro UNI 2023-II?",
    tags: ["Matemáticas", "Simulacro UNI"],
    likes: 24,
    comments: 12,
  },
  {
    author: "María Fernanda",
    ago: "hace 4 horas",
    text: "Comparto mis apuntes de Física. ¡Espero que les sirvan!",
    tags: ["Física", "Apuntes"],
    likes: 58,
    comments: 21,
  },
  {
    author: "Renzo Aguilar",
    ago: "hace 8 horas",
    text: "Racha de 30 días estudiando Razonamiento Verbal. Se puede 💪",
    tags: ["Racha", "Verbal"],
    likes: 96,
    comments: 34,
  },
];

export const ranking = [
  { name: "Camila Torres", xp: 4820 },
  { name: "Daniel Asturrizaga", xp: 4310 },
  { name: "Renzo Aguilar", xp: 3980 },
  { name: "María Fernanda", xp: 3720 },
  { name: "Juan Pablo", xp: 3510 },
];

export const weeklyStudy = [
  { day: "Lun", horas: 2.5 },
  { day: "Mar", horas: 3.2 },
  { day: "Mié", horas: 1.8 },
  { day: "Jue", horas: 4.1 },
  { day: "Vie", horas: 2.9 },
  { day: "Sáb", horas: 5.0 },
  { day: "Dom", horas: 3.4 },
];

export const student = {
  name: "Daniel",
  fullName: "Daniel Asturrizaga",
  level: 12,
  xp: 1500,
  xpGoal: 2000,
  streak: 12,
  overall: 72,
  target: "UNMSM · Ingeniería de Sistemas",
};
