/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as EstrategiasRouteImport } from './routes/estrategias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SimulacrosRouteImport } from './routes/simulacros'
import { Route as UniversidadesRouteImport } from './routes/universidades'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as CursosSlugRouteImport } from './routes/cursos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiasRoute = EstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacrosRoute = SimulacrosRouteImport.update({
  id: '/simulacros',
  path: '/simulacros',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversidadesRoute = UniversidadesRouteImport.update({
  id: '/universidades',
  path: '/universidades',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidad': typeof ComunidadRoute
  '/estrategias': typeof EstrategiasRoute
  '/perfil': typeof PerfilRoute
  '/simulacros': typeof SimulacrosRoute
  '/universidades': typeof UniversidadesRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidad': typeof ComunidadRoute
  '/estrategias': typeof EstrategiasRoute
  '/perfil': typeof PerfilRoute
  '/simulacros': typeof SimulacrosRoute
  '/universidades': typeof UniversidadesRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos': typeof CursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidad': typeof ComunidadRoute
  '/estrategias': typeof EstrategiasRoute
  '/perfil': typeof PerfilRoute
  '/simulacros': typeof SimulacrosRoute
  '/universidades': typeof UniversidadesRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidad'
    | '/estrategias'
    | '/perfil'
    | '/simulacros'
    | '/universidades'
    | '/cursos/$slug'
    | '/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidad'
    | '/estrategias'
    | '/perfil'
    | '/simulacros'
    | '/universidades'
    | '/cursos/$slug'
    | '/cursos'
  id:
    | '__root__'
    | '/'
    | '/comunidad'
    | '/estrategias'
    | '/perfil'
    | '/simulacros'
    | '/universidades'
    | '/cursos/$slug'
    | '/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadRoute: typeof ComunidadRoute
  EstrategiasRoute: typeof EstrategiasRoute
  PerfilRoute: typeof PerfilRoute
  SimulacrosRoute: typeof SimulacrosRoute
  UniversidadesRoute: typeof UniversidadesRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategias': {
      id: '/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof EstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacros': {
      id: '/simulacros'
      path: '/simulacros'
      fullPath: '/simulacros'
      preLoaderRoute: typeof SimulacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universidades': {
      id: '/universidades'
      path: '/universidades'
      fullPath: '/universidades'
      preLoaderRoute: typeof UniversidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadRoute: ComunidadRoute,
  EstrategiasRoute: EstrategiasRoute,
  PerfilRoute: PerfilRoute,
  SimulacrosRoute: SimulacrosRoute,
  UniversidadesRoute: UniversidadesRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
