/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstrategiasRouteImport } from './routes/estrategias'
import { Route as SimulacrosRouteImport } from './routes/simulacros'
import { Route as CursosIndexRouteImport } from './routes/cursos/index'
import { Route as CursosSlugRouteImport } from './routes/cursos/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiasRoute = EstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacrosRoute = SimulacrosRouteImport.update({
  id: '/simulacros',
  path: '/simulacros',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: '/cursos/',
  path: '/cursos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/cursos/$slug',
  path: '/cursos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estrategias': typeof EstrategiasRoute
  '/simulacros': typeof SimulacrosRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estrategias': typeof EstrategiasRoute
  '/simulacros': typeof SimulacrosRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos': typeof CursosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estrategias': typeof EstrategiasRoute
  '/simulacros': typeof SimulacrosRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/cursos/': typeof CursosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estrategias' | '/simulacros' | '/cursos/$slug' | '/cursos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estrategias' | '/simulacros' | '/cursos/$slug' | '/cursos'
  id:
    | '__root__'
    | '/'
    | '/estrategias'
    | '/simulacros'
    | '/cursos/$slug'
    | '/cursos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstrategiasRoute: typeof EstrategiasRoute
  SimulacrosRoute: typeof SimulacrosRoute
  CursosSlugRoute: typeof CursosSlugRoute
  CursosIndexRoute: typeof CursosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategias': {
      id: '/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof EstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacros': {
      id: '/simulacros'
      path: '/simulacros'
      fullPath: '/simulacros'
      preLoaderRoute: typeof SimulacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/cursos/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstrategiasRoute: EstrategiasRoute,
  SimulacrosRoute: SimulacrosRoute,
  CursosSlugRoute: CursosSlugRoute,
  CursosIndexRoute: CursosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
